TDDStory7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('accordio/', include('accordio.urls')),
    path('commentsection/', include('commentSection.urls')),
    path('book/', include('book.urls')),
    path('api/', include('apis.urls')),
]

accordio/urls.py
from django.urls import path
from . import views

app_name = "accordio"

urlpatterns = [
    path('', views.index, name='index'),
]

apis/urls.py
from django.urls import path,include
from . import views
from rest_framework import routers

# router = routers.DefaultRouter()
# router.register('like', views.LikeView)

urlpatterns = [
    path('like/', views.likeOverview, name="likeOverview"),
    path('like/<int:pk>/', views.likeOverviewDetail, name="like-detail")
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path('', views.index, name='index'),
]

commentSection/urls.py
from django.urls import path
from . import views

app_name = "commentSection"

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
]

landingpage/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "landingpage"
urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='landingPage/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/register/', views.register, name='register'),
]

accordio/models.py
from django.db import models

# Create your models here.

apis/models.py
from django.db import models

# Create your models here.
class Like(models.Model):
    bookID = models.CharField(max_length=15)
    bookName = models.CharField(max_length=255, null=True)
    like = models.IntegerField()
    thumbnailBig = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.bookName

book/models.py
from django.db import models

# Create your models here.

commentSection/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    nama = models.CharField(max_length=255)
    komentar = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    color = models.CharField(max_length=7, default="#744f4f")

landingpage/models.py
from django.db import models

# Create your models here.

accordio/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def index(request):
    return render(request, "accordio/index.html")

apis/views.py
from django.shortcuts import render
from rest_framework import viewsets, permissions, status
from .models import Like
from .serializers import LikeSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response


# Create your views here.

# class LikeView(viewsets.ModelViewSet):
#     serializer_class = LikeSerializer
#     queryset = Like.objects.all()

@api_view(['GET', 'POST'])
def likeOverview(request):
    serializer_context = {
        'request': request,
    }
    if request.method == 'GET':
        likes = Like.objects.all()
        serializer = LikeSerializer(likes, many=True, context=serializer_context)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = LikeSerializer(data=request.data, context=serializer_context)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET', 'POST', 'DELETE'])
def likeOverviewDetail(request, pk):
    serializer_context = {
        'request': request,
    }
    try:
        like = Like.objects.get(pk=pk)
    except like.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = LikeSerializer(like, context=serializer_context)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = LikeSerializer(like, data=request.data, context=serializer_context)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        like.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

book/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request):
    return render(request, "book/index.html")

commentSection/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request):
    if request.method == "POST":
        if 'deleteId' in request.POST:
            try:
                deleteComment = Comment.objects.get(id=request.POST['deleteId'])
                deleteComment.delete()
                messages.success(request, "Komentar berhasi di hapus!")
            except:
                messages.error(request, "Wahh.. Terjadi error ni pada website, ayo refresh dulu websitenya!")
        elif 'color' in request.POST:
            comment = Comment.objects.get(id=request.POST['id'])
            comment.color = request.POST['color']
            comment.save()
            messages.success(request, "YAAYYY, tag berhasil dirubah")
    comment = Comment.objects.all().order_by("-id")
    return render(request, "commentSection/index.html", {"commentList" : comment})

@login_required
def create(request):
    if request.method == "POST":
        if request.POST["confirm"] == "false":
            messages.error(request, "Yaaahh, komentar mu batal di post deh!")
            return redirect("/commentsection/")
        data = request.POST
        new_comment = Comment.objects.create(nama=data['nama'], komentar=data['komentar'], color=data['color'])
        new_comment.save()
        messages.success(request, "Yey, komentar kamu berhasil di post!")
        return redirect("/commentsection/")

    form = request.GET
    return render(request, "commentSection/create.html", {'form' : form})

landingpage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.contrib.auth.forms import UserCreationForm

def index(request):
    return render(request, "landingPage/index.html")

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Selamat, Akun {username} telah dibuat!')
            print(username)
            return redirect('landingpage:login')
        else:
            messages.error(request, 'Wahh sepertinya ada yang salah di pengisian data mu!')
            return render(request, 'landingPage/register.html', {"form" : form})
    else:
        form = UserCreationForm()
        return render(request, "landingPage/register.html", {"form" : form})

def loginSuccessMessage(sender, user, request, **kwargs):
    messages.success(request, "Halo " + user.username + "! Kamu berhasil Login.")

def logoutSuccessMessage(sender, user, request, **kwargs):
    messages.success(request, "Terimakasih " + user.username + " telah berkunjung. Dadah!")

user_logged_in.connect(loginSuccessMessage)
user_logged_out.connect(logoutSuccessMessage)

templates/accordio/index.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Accordio{% endblock title %}

{% block body %}
    <div class="accordio-header">
        <h1 class="title">Apa itu Lorem Ipsum?</h1>
        <span>PerePereWere Story 8 Ajigile</span>
    </div>
    <div class="accordio-main">
        <div class="accordio-list">
            <div class="accordio">
                <div class="accordio-title">
                    <div class="title">
                        <h1>Bahasa</h1>
                        <span>Apa itu Lorem Ipsum? (Indo)</span>
                    </div>
                    <div class="button">
                        <button type="button" class="button-up"><img src="{% static 'img/arrow.png' %}" class="up" alt=""></button>
                        <button type="button" class="button-down"><img src="{% static 'img/arrow.png' %}" class="down" alt=""></button>
                    </div>
                </div>
                <div class="accordio-body show">
                    <p>Lorem Ipsum adalah contoh teks atau dummy dalam industri percetakan dan penataan huruf atau typesetting. Lorem Ipsum telah menjadi standar contoh teks sejak tahun 1500an, saat seorang tukang cetak yang tidak dikenal mengambil sebuah kumpulan teks dan mengacaknya untuk menjadi sebuah buku contoh huruf. </p>
                </div>
            </div>
            <div class="accordio">
                <div class="accordio-title">
                    <div class="title">
                        <h1>Melayu</h1>
                        <span>Apa itu Lorem Ipsum? (Malay)</span>
                    </div>
                    <div class="button">
                        <button type="button" class="button-up"><img src="{% static 'img/arrow.png' %}" class="up" alt=""></button>
                        <button type="button" class="button-down"><img src="{% static 'img/arrow.png' %}" class="down" alt=""></button>
                    </div>
                </div>
                <div class="accordio-body">
                    <p>Lorem Ipsum adalah text contoh digunakan didalam industri pencetakan dan typesetting. Lorem Ipsum telah menjadi text contoh semenjak tahun ke 1500an, apabila pencetak yang kurang terkenal mengambil sebuah galeri cetak dan merobakanya menjadi satu buku spesimen.</p>
                </div>
            </div>
            <div class="accordio">
                <div class="accordio-title">
                    <div class="title">
                        <h1>English</h1>
                        <span>What is Lorem Ipsum?</span>
                    </div>
                    <div class="button">
                        <button type="button" class="button-up"><img src="{% static 'img/arrow.png' %}" class="up" alt=""></button>
                        <button type="button" class="button-down"><img src="{% static 'img/arrow.png' %}" class="down" alt=""></button>
                    </div>
                </div>
                <div class="accordio-body">
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                </div>
            </div>
            <div class="accordio">
                <div class="accordio-title">
                    <div class="title">
                        <h1>Italiano</h1>
                        <span>Cos’è Lorem Ipsum?</span>
                    </div>
                    <div class="button">
                        <button type="button" class="button-up"><img src="{% static 'img/arrow.png' %}" class="up" alt=""></button>
                        <button type="button" class="button-down"><img src="{% static 'img/arrow.png' %}" class="down" alt=""></button>
                    </div>
                </div>
                <div class="accordio-body">
                    <p>Lorem Ipsum è un testo segnaposto utilizzato nel settore della tipografia e della stampa. Lorem Ipsum è considerato il testo segnaposto standard sin dal sedicesimo secolo, quando un anonimo tipografo prese una cassetta di caratteri e li assemblò per preparare un testo campione.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

templates/book/index.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Book List{% endblock title %}

{% block body %}
    {% csrf_token %}
    <div class="book-header">
        <h1 class="title">Google Book Store</h1>
        <span>PerePereWere Story 9 (2minggu coy)</span>
    </div>
    <div class="book-main">
        <div class="book-search">
            <h1>Cari Buku...</h1>
            <div class="input-group mb-3">
                <input type="text" class="form-control" id="input-search" placeholder="Masukkan nama buku yang anda cari..." aria-label="Cari" aria-describedby="button-search">
                <div class="input-group-prepend">
                    <button class="btn btn-submit" type="button" id="button-search">Cari</button>
                </div>
            </div>
        </div>
        <div class="leaderboard">
            <button type="button" id="leaderboard-btn" class="btn btn-leaderboard" data-toggle="modal" data-target="#LeaderBoard">
                5 Buku Dengan Rating Terbaik
            </button>
        </div>
        <div class="book-list" id="book-list">
        </div>
        <div class="modal fade" id="LeaderBoard" tabindex="-1" role="dialog" aria-labelledby="LeaderBoardLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="LeaderBoardLabel">LeaderBoard</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  ...
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
    </div>
{% endblock body %}

templates/commentSection/create.html
{% extends 'layout.html' %}

{% block title %}Confirm{% endblock title %}

{% block body %}
    <div class="confirm">
        <div class="header-confirm">
            <h1>Konfirmasi Pesan !!</h1>
        </div>
        <div class="massage">
            <div class="title">
                <h3>Halo {{ form.nama }}!</h3>
                <p>Apakah kamu yakin ingin memasukkan komentar berikut?</p>
            </div>
            <div class="paragraph">
                <span>❛❛</span>
                <div>
                    <p>{{ form.komentar }}</p>
                </div>
                <span>❜❜</span>
            </div>
        </div>
        <div class="button-card">
            <form action="" method="post" id="not_btn">
                {% csrf_token %}
                <input type="hidden" name="confirm" value="false">
                <button type="submit" class="btn btn-back">Tidak! Kembali</button>
            </form>
            <form action="" method="post"  id="yes_btn">
                {% csrf_token %}
                <input type="hidden" name="nama" value="{{ form.nama }}">
                <input type="hidden" name="komentar" value="{{ form.komentar }}">
                <input type="hidden" name="color" value="{{form.color}}">
                <input type="hidden" name="confirm" value="true">
                <button type="submit" class="btn btn-confirm">Iya, Lanjutkan!</button>
            </form>
        </div>
    </div>
{% endblock body %}

templates/commentSection/index.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Comment Section{% endblock title %}

{% block body %}
    <div class="header">
        <div class="title">
            <h1>Komentar Julid</h1>
            <span>PerePereWere Story 7 Anjay</span>
        </div>
    </div>
    <div class="form-main">
        <form action="/commentsection/create" method="get">
            <div class="form-group">
                <label for="name">Nama</label>
                <input type="text" class="form-control" id="name" placeholder="Silahkan masukkan nama anda" autocomplete="off" name="nama" required />
            </div>
            <div class="form-group">
                <label for="comment">Komentar</label>
                <textarea name="komentar" class="form-control" rows="3" id="comment" placeholder="Berikan komentar mu disini!!" required></textarea>
            </div>
           <div class="form-group form-group-radio">
             <div class="label">
               <label>Pilih Tag Komentar Anda</label>
             </div>
             <div class="form-radio">
               <input class="radio-btn" id="smiley" type="radio" name="color" value="#e6e65e">
               <img src="{% static 'img/Emoji/9.png' %}" alt="" class="emoji">
               <label class="radio-label" for="smiley">Smile</label>
              </div>
              <div class="form-radio">
                <input class="radio-btn" id="kiss" type="radio" name="color" value="#e497a5">
                <img src="{% static 'img/Emoji/1.png' %}" alt="" class="emoji">
                <label class="radio-label" for="kiss">Kiss</label>
              </div>
              <div class="form-radio">
                <input class="radio-btn" id="sad" type="radio" name="color" value="#8ba1df">
                <img src="{% static 'img/Emoji/8.png' %}" alt="" class="emoji">
                <label class="radio-label" for="sad">Sad</label>
              </div>
              <div class="form-radio">
                <input class="radio-btn" id="mad" type="radio" name="color" value="#f87575">
                <img src="{% static 'img/Emoji/7.png' %}" alt="" class="emoji">
               <label class="radio-label" for="mad">Angry</label>
             </div>
           </div>
            <button type="submit" class="btn btn-submit">Submit</button>
        </form>
    </div>
    <div class="comment-list">
        <div class="comment">
          {% for comment in commentList %}
            <div class="card my-4" style="box-shadow: -8px 9px 0 -2px {{comment.color}};">
                <div class="card-body">
                  <blockquote class="blockquote mb-0">
                    <p class="comment-body">{{comment.komentar}}</p>
                    <footer class="blockquote-footer">{{comment.nama}}</footer>
                    <div class="option">
                      <img class="emoji-option" src="{% static 'img/Emoji/' %}{% if comment.color == '#e6e65e' %}9.png{% elif comment.color == '#e497a5' %}1.png{% elif comment.color == '#8ba1df' %}8.png{% elif comment.color == '#f87575' %}7.png{% else %}3.png{% endif %}" alt="">
                      <span class="material-icons danger btn-delete" onclick="deleteId({{comment.id}})" data-toggle="modal" data-target="#DeleteModal">delete_outline</span>
                    </div>
                    <div class="floating-tag-option" id="floating{{comment.id}}">
                      <form action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{comment.id}}">
                        <button type="submit" name="color" value="#e6e65e"><img src="{% static 'img/Emoji/9.png' %}" class="emoji-option" alt=""></button>
                        <button type="submit" name="color" value="#e497a5"><img src="{% static 'img/Emoji/1.png' %}" class="emoji-option" alt=""></button>
                        <button type="submit" name="color" value="#8ba1df"><img src="{% static 'img/Emoji/8.png' %}" class="emoji-option" alt=""></button>
                        <button type="submit" name="color" value="#f87575"><img src="{% static 'img/Emoji/7.png' %}" class="emoji-option" alt=""></button>
                      </form>
                    </div>
                  </blockquote>
                </div>
            </div>
          {% endfor %}
        </div>
    </div>

    <div class="confirm-modal">  
      <!-- Modal -->
      <div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="DeleteModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Anda yakin?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Apakah kamu yakin ingin menghapus komentar ini?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Kembali</button>
              <form action="" method="post" id="deleteForm">
                {% csrf_token %}
                <input type="hidden" id="deleteId" name="deleteId" value="">
                <button type="submit" class="btn btn-danger">Hapus</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endblock body %}

templates/landingPage/index.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Welcome{% endblock title %}

{% block body %}
    <div class="landing-header">
        <h1 class="title">Selamat Datang</h1>
        <h2>{% if user.is_authenticated %} Halo {{ user.username }}! {% else %} Login untuk melihat lebih lanjut! {% endif %}</h2>
        <span>ini adalah website pengumpulan pepewe muhammadhafizm</span>
    </div>
    <div class="landing-body">
        <div class="story-link-list">
        {% if user.is_authenticated %}
            <div class="story-link" onclick="location.href='{% url 'commentSection:index' %}'">
                <h3>STORY 7</h3>
                <span>Comment Section (TDD)</span>
            </div>
            <div class="story-link" onclick="location.href='{% url 'accordio:index' %}'">
                <h3>STORY 8</h3>
                <span>Accordion (Js/Jquery)</span>
            </div>
            <div class="story-link" onclick="location.href='{% url 'book:index' %}'">
                <h3>STORY 9</h3>
                <span>Book APIs and Like (Ajax/WebService)</span>
            </div>
        {% endif %}
            <div class="story-link" onclick="location.href='{% if user.is_authenticated%}{% url 'landingpage:logout' %}{% else %}{% url 'landingpage:login' %}{% endif %}'">
                <h3>STORY 10</h3>
                <span>{% if user.is_authenticated %}Logout Here!{% else %}Login and Register Here!{% endif %}</span>
            </div>
        </div>
    </div>
{% endblock body %}

templates/landingPage/login.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock title %}

{% block body %}
    <div class="login">
        <div class="login-register-floating-box">
            <div class="login-register-header">
                <h1 class="title">Login</h1>
                <span>story 10, auth. login untuk melihat lebih lanjut</span>
            </div>
            <div class="login-register-form">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-submit">Login</button>
                </form>
                <hr>
                <div class="other-choice">
                    <span>belum punya akun? Register <a href="{% url 'landingpage:register' %}">disini</a></span>
                    <div class="google-OAuth2">
                    </div>
                <div>
            </div>
        </div>
    </div>
{% endblock body %}

templates/landingPage/register.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Register{% endblock title %}

{% block body %}
    <div class="register">
        <div class="login-register-floating-box">
            <div class="login-register-header">
                <h1 class="title">Sign Up</h1>
                <span>Daftar kan akun barumu disini</span>
            </div>
            <div class="login-register-form">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-submit">Sign Up</button>
                </form>
                <hr>
                <div class="other-choice">
                    <span>Sedah memiliki akun? Sign in <a href="{% url 'landingpage:login' %}">disini</a></span>
                    <div class="google-OAuth2">
                    </div>
                <div>
            </div>
    </div>
    </div>
{% endblock body %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="icon" href="{% static 'img/logo.png' %}">
    <!-- Bootstrapt -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <!-- Font -->
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&display=swap" rel="stylesheet">
    <!-- icon -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
    <div id="main">
        <div class="valid-invalid-feedback">
        {% if messages %}
        {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}" role="alert">
            <h5>{% if message.tags %}{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Yaahhh!!, Error
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}Yeay Berhasil!!{% endif %}{% endif %}</h5>
                <p class="ml-2 feedback">{{ message }}</p>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <section class="navbar">
            <div class="logo"><a href="{% url 'landingpage:index' %}">MHM.</a></div>
            <div class="login-logout">
                {% if user.is_authenticated %}
                <button class="btn btn-logout" onclick="location.href='{% url 'landingpage:logout'%}'">Log Out</button>
                {% else %}
                <button class="btn btn-login" onclick="location.href='{% url 'landingpage:login'%}'">Log In</button>
                <button class="btn btn-register" onclick="location.href='{% url 'landingpage:register'%}'">Register</button>
                {% endif %}
            </div>
        </section>
        <section class="main">
            {% block body %}
            
            {% endblock body %}
        </section>
        <section class="footer">
            <div class="sosmed">
                <a href="https://www.instagram.com/muhammadhafizm/"><img src="{% static 'img/instagram.png' %}" class='sosmed-logo'></a>
                <a href="https://line.me/R/ti/p/muhammadhafizm"><img src="{% static 'img/line.png' %}" class='sosmed-logo'></a>
                <a href="https://www.linkedin.com/in/muhammad-hafiz-maulana-990980157/"><img src="{% static 'img/linkedin.png' %}" class='sosmed-logo'></a>
            </div>
        </section>
        
        <section class="background">
            <span><img src="{% static 'img/Emoji/' %}" class="emoji-background" alt=""></span>
            <span><img src="{% static 'img/Emoji/' %}" class="emoji-background" alt=""></span>
            <span><img src="{% static 'img/Emoji/' %}" class="emoji-background" alt=""></span>
            <span><img src="{% static 'img/Emoji/' %}" class="emoji-background" alt=""></span>
            <span><img src="{% static 'img/Emoji/' %}" class="emoji-background" alt=""></span>
            <span><img src="{% static 'img/Emoji/' %}" class="emoji-background" alt=""></span>
            <span><img src="{% static 'img/Emoji/' %}" class="emoji-background" alt=""></span>
            <span><img src="{% static 'img/Emoji/' %}" class="emoji-background" alt=""></span>
        </section>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>